### ISSUE TITLE
Heterogenously namespaced keywords

### ISSUE THREAD

**Issue by zalky** [stathissideris/spec-provider#20] opened 2018-03-15 21:20 UTC
Hi, thanks for putting together this fantastic library!

I'm having trouble figuring out how to generate specs for entity maps with heterogenously namespaced keywords. For example:

```clj
{:a/b :value
 :c/d "value"}
```

As best I can tell, `spec-provider` assumes that all keys in a map are either un-namespaced, or that they all have the same namespace. Am I missing something?

**Comment by stathissideris** [comment] 2018-04-30 15:47
Confirmed, this is really a bug and it's due to an assumption in the code that had to do with my poor understanding of namespaces and spec when I was first developing spec-provider. Thanks for reporting this, I'm working on a fix.

**Comment by stathissideris** [comment] 2018-04-30 17:36
Fixed in v0.4.14

**Closed as completed by stathissideris** 2018-04-30 17:36 UTC
